---
title: "Grammar of Graphics"
author: "Aaron R. Williams"
output:
  html_document:
    code_folding: hide
    toc: TRUE
    toc_float: TRUE
editor_options:
  chunk_output_type: console
---

```{r}
library(tidyverse)

theme_set(theme_minimal())

```

## Exercise 1

```{r}
tidy_anscombe <- 
  anscombe %>%
  # make the wide data too long
  pivot_longer(
    cols = everything(), 
    names_to = "names", 
    values_to = "value"
  ) %>%
  # split the axis and quartet id
  mutate(
    coord = str_sub(names, start = 1, end = 1),
    quartet = str_sub(names, start = 2, end = 2) 
  ) %>%
  group_by(quartet, coord) %>%
  mutate(id = row_number()) %>%
  # make the data tidy
  pivot_wider(id_cols = c(id, quartet), names_from = coord, values_from = value) %>%
  ungroup() %>%
  select(-id)

## YOUR CODE GOES HERE


ggplot(data = tidy_anscombe, mapping = aes(x = x, y = y)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) + 
  facet_wrap(~ quartet)

```

## Exercise 2

```{r}

titanic <- tribble(
  ~Class, ~Sex, ~n,
  "1st class", "female passengers", 144,
  "1st class", "male passengers", 179,
  "2nd class", "female passengers", 106,
  "2nd class", "male passengers", 171, 
  "3rd class", "female passengers", 216,
  "3rd class", "male passengers", 493
)

## YOUR CODE GOES HERE
titanic %>%
  ggplot(mapping = aes(x = Class, y = n, fill = Sex)) +
  geom_col()
  

```

## Exercise 3


```{r}
## YOUR CODE GOES HERE

# bars are stacked

titanic %>%
  ggplot(mapping = aes(x = Class, y = n, fill = Sex)) +
  geom_col() +
  labs(
    title = "More Men than Women in Titanic deaths",
    caption = "Data from library(titanic)"
  )

```

## Exercise 4

```{r}
# install.packages("ggtext")
library(ggtext)


# YOUR WORK GOES HERE

# bars are next to each other

titanic %>%
  ggplot(mapping = aes(x = Class, y = n, fill = Sex)) +
  geom_col(position = "dodge") +
  labs(
    title = "More Men than Women in Titanic deaths",
    caption = "Data from library(titanic)"
  ) +
  theme(plot.title = element_markdown()) +
  labs(
    title = "More 
    <span style='color:#ADD8E6;'>male passengers</span> died than 
    <span style='color:#FFC0CB;'>female passengers</span> in all three classes",
    x = NULL,
    y = NULL
  ) +
  guides(fill = "none")

```

## Exercise 5

```{r warning = FALSE}
library(gghighlight)
library(gapminder)

data <- gapminder %>%
  filter(continent %in% c("Europe")) %>%
  group_by(country) %>%
  mutate(pcgdp_change = ifelse(year == 1952, 0, gdpPercap - lag(gdpPercap))) %>%
  mutate(pcgdp_change = cumsum(pcgdp_change))

data |>
  ggplot(mapping = aes(x = year, y = pcgdp_change, color = country)) +
  geom_line() +
  gghighlight(max(pcgdp_change) > 35000) +
  scale_x_continuous(
    expand = expansion(mult = c(0.002, 0)),
    breaks = c(seq(1950, 2010, 10)),
    limits = c(1950, 2010)
  ) +
  scale_y_continuous(
    expand = expansion(mult = c(0, 0.002)),
    breaks = 0:8 * 5000,
    labels = scales::dollar,
    limits = c(0, 40000)
  ) +
  labs(
    x = "Year",
    y = "Change in per-capita GDP (US dollars)"
  )


# YOUR WORK GOES HERE

data <- gapminder %>%
  filter(continent %in% c("Europe")) %>%
  group_by(country) %>%
  mutate(pcgdp_change = 
           ifelse(year = 1952, 0, gdpPercap - lag(gdpPercap))) %>%
  mutate(pcgdp_change = cumsum(pcgdp_change)) +
  gghighligh(max(pcgdp_change) > 35000)


  

```
